### ISSUE TITLE
Settings Tab not Appearing in Career mode [0.90]

### ISSUE THREAD

**Issue by Belkon** [malkuth1974/MissionController2#15]
The tab is missing, plus I don't even think the mod works for career mode, no features seem to be working.

**Comment by malkuth1974** [comment]
Not sure what the issue is, if its not installed correct this will happen. I don't have enough info to even begin to try to figure out this issue.

The mod does work in career mode, and does show the icon when its installed the correct way.  Just place the MissionControllerEC folder into your gamedata folder is all that is needed.
